envars: &envars
  env:
    CfLogin: $(CfLogin)
    CfPassword: $(CfPassword)
    CfOrg: $(CfOrg)
    CfSpace: $(CfSpace)
    

stages:
  - stage: Build
    jobs:
      - job: compile
        steps:
          - script: ./build.sh Publish --skip
          - script: ./build.sh Pack --skip
          - task: PublishPipelineArtifact@0
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifactName: Publish artifacts
  - stage: Deploy Dev
    jobs:
      - deployment: Deploy Dev
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: ./build.sh Login --skip
                  <<: *envars
                - script: ./build.sh Deploy --skip
                  <<: *envars
