

stages:
  - stage: Build
    jobs:
      - job: compile
        steps:
          - script: ./build.sh Publish --skip
          - script: ./build.sh Pack --skip
          - task: PublishPipelineArtifact@0
            inputs:
              targetPath: $(Build.ArtifactStagingDirectory)
              artifactName: Publish artifacts
  - stage: Dev
    jobs:
      - deployment: Dev
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - script: ./build.sh Login --skip
                  env:
                    CfLogin: $(CfLogin)
                    CfPassword: $(CfPassword)
                    CfOrg: $(CfOrg)
                    CfSpace: $(CfSpace)
                - script: ./build.sh Deploy --skip
                  env:
                    CfLogin: $(CfLogin)
                    CfPassword: $(CfPassword)
                    CfOrg: $(CfOrg)
                    CfSpace: $(CfSpace)
