---
resources:
- name: git-src
  type: git
  source:
    uri: https://github.com/macsux/pcf-ers-dotnetcore-demo.git
    branch: master
jobs:
  - name: job
    public: true
    plan:
      - get: git-src
      - task: simple-task
        config:
          inputs:
          - name: git-src
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: mcr.microsoft.com/dotnet/core/sdk }
          run:
            dir: git-src
            path: ./build.sh
            args: ["Pack"]
      - task: another task
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: mcr.microsoft.com/dotnet/core/sdk }
          run:
            path: echo
            args: ["Blah!"]