---
task-image: &task-image
  platform: linux
  image_resource:
    type: docker-image
    source: 
        repository: macsux/dotnet
        tag: 2.2-sdk
        
resources:
- name: git-src
  type: git
  source:
    uri: https://github.com/macsux/pcf-ers-dotnetcore-demo.git
    branch: master

jobs:
  - name: job
    public: true
    plan:
      - get: git-src
      - task: Build
        config:
          inputs:
          - name: git-src
          <<: *task-image
          run:
            dir: git-src
            path: ./build.sh
            args: ["Pack"]
      - task: Push
        config:
          platform: linux
          <<: *task-image
          run:
            dir: git-src
            path: ./build.sh
            args: ["CfPush"]