name: MyPipeline
stages:
- jobs:
  - job: Build
    steps:
    - name: Publish
      script: build.sh Publish --skip
    - name: Pack
      script: build.sh Pack --skip
    - task: PublishPipelineArtifact1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)\artifacts
        artifactName: artifacts
  stageStage: Build
